export const metadata = {
  title: "Terms of Service — AI World Cup Oracle",
  description: "Terms of service for the AI World Cup Oracle prediction card generator.",
};

export default function TermsPage() {
  return (
    <main className="relative min-h-screen px-4 py-16 overflow-hidden">
      <div className="absolute top-1/3 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[600px] h-[600px] rounded-full bg-neon/5 blur-[120px] pointer-events-none" />

      <div className="relative z-10 w-full max-w-2xl mx-auto">
        <h1 className="text-4xl sm:text-5xl font-black tracking-tight mb-2">
          Terms of <span className="text-neon">Service</span>
        </h1>
        <p className="text-zinc-500 text-sm mb-10">Last updated: June 25, 2026</p>

        <div className="prose prose-invert prose-zinc max-w-none space-y-6 text-zinc-400 text-sm leading-relaxed">
          <section>
            <h2 className="text-lg font-bold text-zinc-100 mt-8 mb-3">1. Acceptance of Terms</h2>
            <p>
              By accessing or using AI World Cup Oracle (&ldquo;the Service&rdquo;), you agree to be bound by these
              Terms of Service. If you do not agree, do not use the Service.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-zinc-100 mt-8 mb-3">2. Description of Service</h2>
            <p>
              AI World Cup Oracle provides AI-generated football match predictions and shareable prediction cards for
              the FIFA World Cup 2026 tournament. Predictions are generated by artificial intelligence and are for
              entertainment purposes only.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-zinc-100 mt-8 mb-3">3. Eligibility</h2>
            <p>
              You must be at least 13 years old to use the Service. By using the Service, you represent that you meet
              this age requirement.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-zinc-100 mt-8 mb-3">4. No Gambling or Betting</h2>
            <p>
              The Service provides entertainment content only. Predictions are not intended for use in sports betting,
              gambling, or any activity involving real money wagers. We do not endorse or encourage gambling of any kind.
              You agree not to use our predictions for betting purposes.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-zinc-100 mt-8 mb-3">5. Intellectual Property</h2>
            <p>
              The prediction cards, website design, code, and original content are owned by AI World Cup Oracle. FIFA
              World Cup and team names are trademarks of their respective owners. User-generated prediction cards may be
              shared on social media with attribution.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-zinc-100 mt-8 mb-3">6. Payments and HD Unlock</h2>
            <p>
              The HD Unlock is a one-time payment of $2.99 USD that removes the watermark from your prediction card and
              enables PNG download. All payments are processed securely through PayPal. We do not store your
              payment card details.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-zinc-100 mt-8 mb-3">7. Disclaimer of Warranties</h2>
            <p>
              The Service is provided &ldquo;as is&rdquo; without warranties of any kind. AI-generated predictions may
              be inaccurate. We do not guarantee that the Service will be uninterrupted, error-free, or that predictions
              will match actual match outcomes.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-zinc-100 mt-8 mb-3">8. Limitation of Liability</h2>
            <p>
              To the fullest extent permitted by law, AI World Cup Oracle shall not be liable for any indirect,
              incidental, special, consequential, or punitive damages arising from your use of the Service, including
              any losses related to betting or gambling activities.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-zinc-100 mt-8 mb-3">9. Changes to Terms</h2>
            <p>
              We reserve the right to update these Terms at any time. Continued use of the Service after changes
              constitutes acceptance of the new Terms. We will post notice of material changes on the website.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-zinc-100 mt-8 mb-3">10. Contact</h2>
            <p>
              Questions about these Terms? Contact us at{" "}
              <a href="mailto:zhangrich5@gmail.com" className="text-neon hover:underline">
                zhangrich5@gmail.com
              </a>
              .
            </p>
          </section>
        </div>
      </div>
    </main>
  );
}
